"""orin/v1 wire protocol: framing, message schemas, strict parsing.

Frozen by ``docs/security/orin/ORIN_STAGE_A_SPEC.md`` §3. Transport is a
Unix domain socket with 4-byte big-endian length-prefixed JSON frames of
at most 64 KiB. Every post-handshake message is HMAC-SHA256 authenticated
with a per-connection session key and carries a monotonic sequence number
plus a session nonce; regression or replay disconnects the peer.

Stage A message set is frozen at six types: ``hello``, ``issue``,
``consume``, ``revoke``, ``heartbeat``, ``freeze``. Extra capabilities ride
in payload fields (e.g. ``consume.mode``). Stage B (ORIN_STAGE_B_SPEC.md §2)
extends the vocabulary behind hello ``caps`` negotiation: peers that never
advertise a stage-B cap cannot send or receive its message type — a stage-B
type from a peer without the cap drops the connection.

Parsing is strict per K§8.1: unknown fields are rejected, JSON depth is
capped at 16, string fields have length caps, and numeric fields have range
checks.
"""

from __future__ import annotations

import hashlib
import hmac
import json
import re
from dataclasses import dataclass
from typing import Any, Final

PROTOCOL_VERSION: Final[int] = 1
"""Only orin/v1 exists in Stage A; other versions are rejected at hello."""

MAX_FRAME_BYTES: Final[int] = 64 * 1024
"""Single frame upper bound; over-limit frames drop the connection."""

MAX_JSON_DEPTH: Final[int] = 16
"""Maximum nesting depth accepted when parsing any frame payload."""

MAX_STRING_LENGTH: Final[int] = 8 * 1024
"""Default cap for free-form string fields (identifier fields are tighter)."""

MAX_SEQ: Final[int] = (1 << 64) - 1

MAC_PREFIX: Final[str] = "orin-hmac-sha256:"
"""Prefix of every authenticated message MAC field value."""

SESSION_KEY_BYTES: Final[int] = 32
"""Session key length generated by orind per connection."""

NONCE_HEX_LENGTH: Final[int] = 32
"""16 bytes hex-encoded; both sides contribute one nonce per session."""

MESSAGE_TYPES: Final[frozenset[str]] = frozenset(
    {
        "hello",
        "hello_ack",
        "issue",
        "issue_ack",
        "consume",
        "consume_ack",
        "revoke",
        "revoke_ack",
        "heartbeat",
        "heartbeat_ack",
        "freeze",
        "freeze_ack",
        # -- stage B (B spec §2.3; each requires its negotiated cap) ----------
        "intent",
        "intent_ack",
        "handle",
        "handle_ack",
        "draft",
        "draft_ack",
        "preflight",
        "preflight_ack",
        "commit",
        "commit_ack",
        "receipt",
        "receipt_ack",
        "reconcile",
        "reconcile_ack",
    }
)
"""Full request/ack vocabulary: six frozen Stage A types plus Stage B."""

CLIENT_CAPS: Final[tuple[str, ...]] = ("lease.v2",)
"""Capabilities the Stage A client advertises at hello."""

SERVER_CAPS: Final[tuple[str, ...]] = ("lease.v2",)
"""Capabilities the Stage A orind advertises at hello_ack."""

STAGE_B_CLIENT_CAPS: Final[tuple[str, ...]] = (
    "lease.v2",
    "intent.v1",
    "handle.v1",
    "draft.v1",
    "commit.v1",
)
"""Extra caps an Echo/AppShell client advertises when stage_b is enabled."""

STAGE_B_SERVER_CAPS: Final[tuple[str, ...]] = STAGE_B_CLIENT_CAPS
CELL_CONNECT_CAPS: Final[tuple[str, ...]] = (
    "cell.build",
    "cell.desktop",
    "cell.file",
    "cell.memory",
    "cell.net",
    "cell.secret",
    "cell.connector",
)
"""Identity caps a Cell declares when connecting back to orind."""

# -- token bucket / queue guards (A §3.1) ------------------------------------
RATE_LIMIT_PER_SECOND: Final[int] = 100
RATE_LIMIT_BURST: Final[int] = 200
SERVER_QUEUE_DEPTH: Final[int] = 1024

VERDICTS: Final[frozenset[str]] = frozenset({"allow", "approval_required", "deny", "freeze"})
"""consume_ack verdict vocabulary (WP2 fills approval/deny paths)."""

GATE_VERDICTS: Final[frozenset[str]] = frozenset(
    {
        "allow_read",
        "allow_stage",
        "require_approval",
        "require_dual_control",
        "deny_policy",
        "deny_missing_witness",
        "deny_stale_state",
        "defer_reconciliation",
    }
)
"""Gate Kernel result classes (K§7.7); models only ever see these labels."""

CONSUME_MODES: Final[frozenset[str]] = frozenset(
    {"verify", "preflight", "consume", "context", "scan", "cell"}
)
"""consume request sub-modes covering the LeaseAuthority method surface.

``cell`` (stage B, WP7): authorize-then-proxy an effect into a scheduled
Effect Cell. It carries no lease consumption of its own — the execution
context verifier already spent the lease at the registry boundary — only
the deterministic policy table decides, then orind proxies the payload.
"""

ERROR_CODES: Final[frozenset[str]] = frozenset(
    {
        "bad_message",
        "unknown_lease",
        "mac_invalid",
        "replay",
        "expired",
        "revoked",
        "exhausted",
        "binding_mismatch",
        "context_mismatch",
        "parent_missing",
        "denied",
        "policy_deny",
        "approval_required",
        "export_gate",
        "readonly_mode",
        "frozen",
        "rate_limited",
        "unsupported",
        "internal",
        "unknown_intent",
        "unknown_handle",
        "stale_state",
        "backpressure",
    }
)
"""Error-code vocabulary carried by failed acks (``ok=false``)."""

REVOKE_OPS: Final[frozenset[str]] = frozenset({"lease", "session", "active_sessions", "is_revoked"})
"""Payload ops on the revoke message: two mutations, two queries."""

INTENT_OPS: Final[frozenset[str]] = frozenset(
    {"register", "active", "admin_unfreeze", "grant_export", "grant_exact"}
)
HANDLE_OPS: Final[frozenset[str]] = frozenset({"issue", "resolve", "seed_list"})
RECONCILE_STATES: Final[frozenset[str]] = frozenset({"committed", "absent", "unknown"})

REQUIRED_CAP: Final[dict[str, str]] = {
    "intent": "intent.v1",
    "intent_ack": "intent.v1",
    "handle": "handle.v1",
    "handle_ack": "handle.v1",
    "draft": "draft.v1",
    "draft_ack": "draft.v1",
    "preflight": "commit.v1",
    "preflight_ack": "commit.v1",
    "commit": "commit.v1",
    "commit_ack": "commit.v1",
    "receipt": "commit.v1",
    "receipt_ack": "commit.v1",
    "reconcile": "commit.v1",
    "reconcile_ack": "commit.v1",
}
"""Stage-B message type → hello cap that must have been negotiated."""

HEARTBEAT_INTERVAL_S: Final[float] = 10.0
"""Heartbeat cadence; the connection is the real liveness signal."""

REQUEST_TIMEOUT_S: Final[float] = 10.0
"""Independent RPC timeout; do not couple request waits to heartbeat cadence."""

_LEASE_MAC_RE: Final[re.Pattern[str]] = re.compile(r"^[0-9a-f]{64}$")
"""Lease MAC in wire dicts is bare hex (same as the JSONL ledger payload)."""
_SHA256_PREFIX_RE: Final[re.Pattern[str]] = re.compile(r"^sha256:[0-9a-f]{64}$")
_HEX64_RE: Final[re.Pattern[str]] = re.compile(r"^[0-9a-f]{64}$")
_NONCE_RE: Final[re.Pattern[str]] = re.compile(r"^[0-9a-zA-Z]{16,64}$")


@dataclass(slots=True)
class EchoContextPayload:
    """Duck-typed tool execution context shared by client and daemon.

    ``sign_tool_execution_context`` reads these attributes via ``getattr``,
    so neither side imports the other's context dataclass.
    """

    product_id: str
    owner_key_hash: str
    session_id: str
    run_id: str
    profile: str
    tool_name: str
    args_hash: str
    resource_scope: str
    fs_roots: tuple[str, ...]
    network_policy: str
    network_hosts: tuple[str, ...]
    max_bytes: int
    max_duration_ms: int
    lease_id: str = ""
    lease_mac: str = ""
    signature: str = ""


class ProtocolError(Exception):
    """Malformed, unauthenticated, or replayed protocol message."""


class FieldSpec:
    """One strictly-validated message field."""

    __slots__ = ("name", "kinds", "optional", "max_len", "lo", "hi")

    def __init__(
        self,
        name: str,
        *,
        kinds: tuple[type, ...],
        optional: bool = False,
        max_len: int = MAX_STRING_LENGTH,
        lo: int = 0,
        hi: int = MAX_SEQ,
    ) -> None:
        self.name = name
        self.kinds = kinds
        self.optional = optional
        self.max_len = max_len
        self.lo = lo
        self.hi = hi


_S = (str,)
_I = (int,)

_SCHEMA: Final[dict[str, tuple[FieldSpec, ...]]] = {
    # -- handshake (unauthenticated; MAC starts after hello_ack) -------------
    "hello": (
        FieldSpec("v", kinds=_I, lo=1, hi=PROTOCOL_VERSION),
        FieldSpec("type", kinds=_S, max_len=16),
        FieldSpec("caps", kinds=(list,), optional=True),
        FieldSpec("pid", kinds=_I, optional=True, lo=1),
    ),
    "hello_ack": (
        FieldSpec("v", kinds=_I, lo=1, hi=PROTOCOL_VERSION),
        FieldSpec("type", kinds=_S, max_len=16),
        FieldSpec("ok", kinds=(bool,), optional=True),
        FieldSpec("code", kinds=_S, optional=True, max_len=32),
        FieldSpec("reason", kinds=_S, optional=True),
        FieldSpec("caps", kinds=(list,), optional=True),
        FieldSpec("server_nonce", kinds=_S, optional=True, max_len=NONCE_HEX_LENGTH),
    ),
    # -- lease issuance -------------------------------------------------------
    "issue": (
        FieldSpec("v", kinds=_I, lo=1, hi=PROTOCOL_VERSION),
        FieldSpec("type", kinds=_S, max_len=16),
        FieldSpec("lease", kinds=(dict,), optional=True),
        FieldSpec("context", kinds=(dict,), optional=True),
        FieldSpec("context_taint", kinds=_I, optional=True),
        FieldSpec("arg_taint", kinds=_I, optional=True),
        FieldSpec("clearance", kinds=_I, optional=True, lo=0, hi=2),
        FieldSpec("channel", kinds=_S, optional=True, max_len=128),
    ),
    "issue_ack": (
        FieldSpec("v", kinds=_I, lo=1, hi=PROTOCOL_VERSION),
        FieldSpec("type", kinds=_S, max_len=16),
        FieldSpec("ok", kinds=(bool,), optional=True),
        FieldSpec("code", kinds=_S, optional=True, max_len=32),
        FieldSpec("reason", kinds=_S, optional=True),
        FieldSpec("lease", kinds=(dict,), optional=True),
        FieldSpec("context_signature", kinds=_S, optional=True, max_len=128),
        FieldSpec("receipt_id", kinds=_S, optional=True, max_len=128),
    ),
    # -- lease consumption ----------------------------------------------------
    "consume": (
        FieldSpec("v", kinds=_I, lo=1, hi=PROTOCOL_VERSION),
        FieldSpec("type", kinds=_S, max_len=16),
        FieldSpec("mode", kinds=_S, max_len=16),
        FieldSpec("lease", kinds=(dict,), optional=True),
        FieldSpec("context", kinds=(dict,), optional=True),
        FieldSpec("expected", kinds=(dict,), optional=True),
        FieldSpec("context_taint", kinds=_I, optional=True),
        FieldSpec("arg_taint", kinds=_I, optional=True),
        FieldSpec("clearance", kinds=_I, optional=True, lo=0, hi=2),
        FieldSpec("scan_text", kinds=_S, optional=True),
        FieldSpec("scan_surface", kinds=_S, optional=True, max_len=16),
        FieldSpec("session_id", kinds=_S, optional=True, max_len=128),
        FieldSpec("payload", kinds=(dict,), optional=True),
        FieldSpec("channel", kinds=_S, optional=True, max_len=128),
    ),
    "consume_ack": (
        FieldSpec("v", kinds=_I, lo=1, hi=PROTOCOL_VERSION),
        FieldSpec("type", kinds=_S, max_len=16),
        FieldSpec("ok", kinds=(bool,), optional=True),
        FieldSpec("code", kinds=_S, optional=True, max_len=32),
        FieldSpec("reason", kinds=_S, optional=True),
        FieldSpec("verdict", kinds=_S, optional=True, max_len=32),
        FieldSpec("receipt", kinds=(dict,), optional=True),
        FieldSpec("receipt_id", kinds=_S, optional=True, max_len=128),
        FieldSpec("policy_version", kinds=_I, optional=True),
        # WP7 cell mode: the finished (untrusted) tool-result envelope.
        FieldSpec("cell", kinds=(dict,), optional=True),
    ),
    # -- revocation -----------------------------------------------------------
    "revoke": (
        FieldSpec("v", kinds=_I, lo=1, hi=PROTOCOL_VERSION),
        FieldSpec("type", kinds=_S, max_len=16),
        FieldSpec("op", kinds=_S, optional=True, max_len=32),
        FieldSpec("lease_id", kinds=_S, optional=True, max_len=64),
        FieldSpec("owner_key_hash", kinds=_S, optional=True),
        FieldSpec("session_id", kinds=_S, optional=True),
    ),
    "revoke_ack": (
        FieldSpec("v", kinds=_I, lo=1, hi=PROTOCOL_VERSION),
        FieldSpec("type", kinds=_S, max_len=16),
        FieldSpec("ok", kinds=(bool,), optional=True),
        FieldSpec("code", kinds=_S, optional=True, max_len=32),
        FieldSpec("reason", kinds=_S, optional=True),
        FieldSpec("revoked", kinds=(list,), optional=True),
        FieldSpec("sessions", kinds=(list,), optional=True),
        FieldSpec("is_revoked", kinds=(bool,), optional=True),
        FieldSpec("receipt_id", kinds=_S, optional=True, max_len=128),
    ),
    # -- heartbeat ------------------------------------------------------------
    "heartbeat": (
        FieldSpec("v", kinds=_I, lo=1, hi=PROTOCOL_VERSION),
        FieldSpec("type", kinds=_S, max_len=16),
    ),
    "heartbeat_ack": (
        FieldSpec("v", kinds=_I, lo=1, hi=PROTOCOL_VERSION),
        FieldSpec("type", kinds=_S, max_len=16),
        FieldSpec("ok", kinds=(bool,), optional=True),
        FieldSpec("code", kinds=_S, optional=True, max_len=32),
        FieldSpec("reason", kinds=_S, optional=True),
        FieldSpec("healthy", kinds=(bool,), optional=True),
    ),
    # -- freeze (orind → client one-way command; ack for test tooling) -------
    "freeze": (
        FieldSpec("v", kinds=_I, lo=1, hi=PROTOCOL_VERSION),
        FieldSpec("type", kinds=_S, max_len=16),
        FieldSpec("reason_code", kinds=_S, optional=True, max_len=64),
    ),
    "freeze_ack": (
        FieldSpec("v", kinds=_I, lo=1, hi=PROTOCOL_VERSION),
        FieldSpec("type", kinds=_S, max_len=16),
        FieldSpec("ok", kinds=(bool,), optional=True),
        FieldSpec("code", kinds=_S, optional=True, max_len=32),
        FieldSpec("reason", kinds=_S, optional=True),
    ),
    # -- stage B: owner intent (intent.v1) -----------------------------------
    "intent": (
        FieldSpec("v", kinds=_I, lo=1, hi=PROTOCOL_VERSION),
        FieldSpec("type", kinds=_S, max_len=16),
        FieldSpec("op", kinds=_S, max_len=32),
        FieldSpec("intent", kinds=(dict,), optional=True),
        FieldSpec("grant", kinds=(dict,), optional=True),
        FieldSpec("task_id", kinds=_S, optional=True, max_len=256),
        FieldSpec("session_id", kinds=_S, optional=True, max_len=128),
    ),
    "intent_ack": (
        FieldSpec("v", kinds=_I, lo=1, hi=PROTOCOL_VERSION),
        FieldSpec("type", kinds=_S, max_len=16),
        FieldSpec("ok", kinds=(bool,), optional=True),
        FieldSpec("code", kinds=_S, optional=True, max_len=32),
        FieldSpec("reason", kinds=_S, optional=True),
        FieldSpec("intent", kinds=(dict,), optional=True),
        FieldSpec("unfrozen", kinds=(list,), optional=True),
    ),
    # -- stage B: handles (handle.v1) ------------------------------------------
    "handle": (
        FieldSpec("v", kinds=_I, lo=1, hi=PROTOCOL_VERSION),
        FieldSpec("type", kinds=_S, max_len=16),
        FieldSpec("op", kinds=_S, max_len=16),
        FieldSpec("kind", kinds=_S, optional=True, max_len=32),
        FieldSpec("spec", kinds=(dict,), optional=True),
        FieldSpec("handle", kinds=(dict,), optional=True),
    ),
    "handle_ack": (
        FieldSpec("v", kinds=_I, lo=1, hi=PROTOCOL_VERSION),
        FieldSpec("type", kinds=_S, max_len=16),
        FieldSpec("ok", kinds=(bool,), optional=True),
        FieldSpec("code", kinds=_S, optional=True, max_len=32),
        FieldSpec("reason", kinds=_S, optional=True),
        FieldSpec("handle", kinds=(dict,), optional=True),
        FieldSpec("candidates", kinds=(list,), optional=True),
    ),
    # -- stage B: drafts (draft.v1) --------------------------------------------
    "draft": (
        FieldSpec("v", kinds=_I, lo=1, hi=PROTOCOL_VERSION),
        FieldSpec("type", kinds=_S, max_len=16),
        FieldSpec("draft", kinds=(dict,)),
        FieldSpec("context_taint", kinds=_I, optional=True),
        FieldSpec("arg_taint", kinds=_I, optional=True),
        FieldSpec("clearance", kinds=_I, optional=True, lo=0, hi=2),
    ),
    "draft_ack": (
        FieldSpec("v", kinds=_I, lo=1, hi=PROTOCOL_VERSION),
        FieldSpec("type", kinds=_S, max_len=16),
        FieldSpec("ok", kinds=(bool,), optional=True),
        FieldSpec("code", kinds=_S, optional=True, max_len=32),
        FieldSpec("reason", kinds=_S, optional=True),
        FieldSpec("verdict", kinds=_S, optional=True, max_len=32),
        FieldSpec("missing", kinds=(list,), optional=True),
        FieldSpec("witness", kinds=(dict,), optional=True),
        # Orin-recomputed canonical effect hash (export-pass binding).
        FieldSpec("payload_hash", kinds=_S, optional=True, max_len=71),
    ),
    # -- stage B: preflight / commit / receipt / reconcile (commit.v1) --------
    "preflight": (
        FieldSpec("v", kinds=_I, lo=1, hi=PROTOCOL_VERSION),
        FieldSpec("type", kinds=_S, max_len=16),
        FieldSpec("draft_id", kinds=_S, max_len=256),
        # Client -> orind may include an advisory executor_id for backwards
        # compatibility, but orind derives the authoritative executor from
        # the sealed manifest.  Orind -> Cell carries both this id and the
        # independently parsed package.  Role-specific requirements are
        # enforced at the two socket boundaries, not by this common parser.
        FieldSpec("executor_id", kinds=_S, optional=True, max_len=128),
        FieldSpec("package", kinds=(dict,), optional=True),
        FieldSpec("session_id", kinds=_S, optional=True, max_len=128),
    ),
    "preflight_ack": (
        FieldSpec("v", kinds=_I, lo=1, hi=PROTOCOL_VERSION),
        FieldSpec("type", kinds=_S, max_len=16),
        FieldSpec("ok", kinds=(bool,), optional=True),
        FieldSpec("code", kinds=_S, optional=True, max_len=32),
        FieldSpec("reason", kinds=_S, optional=True),
        FieldSpec("witness", kinds=(dict,), optional=True),
        # A Cell may return a bounded, authority-free observation projection.
        # Desktop target sealing itself still uses the existing handle frame.
        FieldSpec("result", kinds=(dict,), optional=True),
    ),
    "commit": (
        FieldSpec("v", kinds=_I, lo=1, hi=PROTOCOL_VERSION),
        FieldSpec("type", kinds=_S, max_len=16),
        FieldSpec("permit", kinds=(dict,)),
        # Stage-B non-Build Cells require this peer field.  It deliberately
        # remains optional in the shared schema so the frozen WP7 Build frame
        # (commit(permit=<legacy payload>)) is byte-for-byte compatible.
        FieldSpec("package", kinds=(dict,), optional=True),
    ),
    "commit_ack": (
        FieldSpec("v", kinds=_I, lo=1, hi=PROTOCOL_VERSION),
        FieldSpec("type", kinds=_S, max_len=16),
        FieldSpec("ok", kinds=(bool,), optional=True),
        FieldSpec("code", kinds=_S, optional=True, max_len=32),
        FieldSpec("reason", kinds=_S, optional=True),
        FieldSpec("receipt_id", kinds=_S, optional=True, max_len=128),
        # WP7: bounded untrusted tool output rides here for build results;
        # it is TOOL_RESULT-tainted downstream and never secret material.
        FieldSpec("output", kinds=_S, optional=True, max_len=64 * 1024),
        FieldSpec("result", kinds=(dict,), optional=True),
    ),
    "receipt": (
        FieldSpec("v", kinds=_I, lo=1, hi=PROTOCOL_VERSION),
        FieldSpec("type", kinds=_S, max_len=16),
        FieldSpec("receipt", kinds=(dict,)),
    ),
    "receipt_ack": (
        FieldSpec("v", kinds=_I, lo=1, hi=PROTOCOL_VERSION),
        FieldSpec("type", kinds=_S, max_len=16),
        FieldSpec("ok", kinds=(bool,), optional=True),
        FieldSpec("code", kinds=_S, optional=True, max_len=32),
        FieldSpec("reason", kinds=_S, optional=True),
    ),
    "reconcile": (
        FieldSpec("v", kinds=_I, lo=1, hi=PROTOCOL_VERSION),
        FieldSpec("type", kinds=_S, max_len=16),
        FieldSpec("effect_id", kinds=_S, max_len=256),
        FieldSpec("probe", kinds=(dict,), optional=True),
    ),
    "reconcile_ack": (
        FieldSpec("v", kinds=_I, lo=1, hi=PROTOCOL_VERSION),
        FieldSpec("type", kinds=_S, max_len=16),
        FieldSpec("ok", kinds=(bool,), optional=True),
        FieldSpec("code", kinds=_S, optional=True, max_len=32),
        FieldSpec("reason", kinds=_S, optional=True),
        FieldSpec("state", kinds=_S, optional=True, max_len=16),
        FieldSpec("before_digest", kinds=_S, optional=True, max_len=71),
        FieldSpec("after_digest", kinds=_S, optional=True, max_len=71),
        FieldSpec("target_digest", kinds=_S, optional=True, max_len=71),
    ),
}

ENVELOPE_FIELDS: Final[tuple[FieldSpec, ...]] = (
    FieldSpec("v", kinds=_I, lo=1, hi=PROTOCOL_VERSION),
    FieldSpec("type", kinds=_S, max_len=16),
    FieldSpec("seq", kinds=_I, lo=1),
    FieldSpec("nonce", kinds=_S, max_len=NONCE_HEX_LENGTH * 2),
    FieldSpec("mac", kinds=_S, optional=True, max_len=len(MAC_PREFIX) + 64),
)

UNAUTHENTICATED_TYPES: Final[frozenset[str]] = frozenset({"hello", "hello_ack"})


def _validate_ack_semantics(envelope: dict[str, Any]) -> None:
    """Check ``ok``/``code`` consistency and success payloads on acks."""

    message_type = envelope["type"]
    if not message_type.endswith("_ack"):
        return
    ok = envelope.get("ok", True)
    code = envelope.get("code")
    if not ok:
        if code is None:
            raise ProtocolError("failed acks require a 'code'")
        if code not in ERROR_CODES:
            raise ProtocolError(f"unknown error code {code!r}")
        return
    if code is not None:
        raise ProtocolError("'code' must be absent on successful acks")
    if message_type == "hello_ack" and "server_nonce" not in envelope:
        raise ProtocolError("successful hello_ack requires 'server_nonce'")
    if message_type == "issue_ack":
        for field in ("lease", "context_signature", "receipt_id"):
            if field not in envelope:
                raise ProtocolError(f"successful issue_ack requires {field!r}")
        validate_lease_dict(envelope["lease"])
    if message_type == "consume_ack":
        verdict = envelope.get("verdict")
        if verdict not in VERDICTS:
            raise ProtocolError("consume_ack verdict must be a known verdict")


def _validate_revoke_semantics(envelope: dict[str, Any]) -> None:
    """Check op/field consistency on revoke requests and revoke_ack replies."""

    message_type = envelope["type"]
    if message_type == "revoke":
        op = envelope.get("op") or _infer_revoke_op(envelope)
        if op not in REVOKE_OPS:
            raise ProtocolError(f"unknown revoke op {op!r}")
        if op == "lease" and not envelope.get("lease_id"):
            raise ProtocolError("revoke op 'lease' requires 'lease_id'")
        if op == "session" and not (envelope.get("owner_key_hash") and envelope.get("session_id")):
            raise ProtocolError("revoke op 'session' requires owner and session")
        if op == "active_sessions" and not envelope.get("owner_key_hash"):
            raise ProtocolError("revoke op 'active_sessions' requires 'owner_key_hash'")
        if op == "is_revoked" and not envelope.get("lease_id"):
            raise ProtocolError("revoke op 'is_revoked' requires 'lease_id'")
    elif message_type == "revoke_ack":
        if envelope.get("ok", True):
            has_result = any(key in envelope for key in ("revoked", "sessions", "is_revoked"))
            if not has_result:
                raise ProtocolError("successful revoke_ack requires a result field")


def _validate_stageb_semantics(envelope: dict[str, Any]) -> None:
    """Op/field consistency for Stage B messages (deep sub-schemas live in
    ``js.orin.intent`` / ``js.orin.handles`` / ``js.orin.draft``)."""

    message_type = envelope["type"]
    if message_type == "intent":
        op = envelope.get("op")
        if op not in INTENT_OPS:
            raise ProtocolError(f"unknown intent op {op!r}")
        intent = envelope.get("intent")
        grant = envelope.get("grant")
        if op in {"grant_export", "grant_exact"}:
            if not isinstance(grant, dict):
                raise ProtocolError(f"{op} requires a 'grant' object")
            if envelope.get("task_id") is None:
                raise ProtocolError(f"{op} requires 'task_id'")
            if op == "grant_exact" and not str(envelope["task_id"]).startswith("task:"):
                raise ProtocolError("grant_exact requires a bounded 'task:' id")
            if intent is not None:
                raise ProtocolError(f"{op} carries fields, not an 'intent' object")
            if op == "grant_exact" and envelope.get("session_id") is not None:
                raise ProtocolError("grant_exact must not carry 'session_id'")
        elif op in ("register", "admin_unfreeze"):
            if not isinstance(intent, dict):
                raise ProtocolError(f"intent op {op!r} requires an 'intent' object")
            if op == "register" and grant is not None:
                if not isinstance(grant, dict):
                    raise ProtocolError("intent register 'grant' must be an object")
                session_id = envelope.get("session_id")
                if not isinstance(session_id, str) or not session_id:
                    raise ProtocolError("intent register with 'grant' requires 'session_id'")
            elif grant is not None:
                raise ProtocolError(f"intent op {op!r} must not carry a 'grant' object")
        elif intent is not None:
            raise ProtocolError(f"intent op {op!r} must not carry an 'intent' object")
        elif grant is not None:
            raise ProtocolError(f"intent op {op!r} must not carry a 'grant' object")
    elif message_type == "handle":
        op = envelope.get("op")
        if op not in HANDLE_OPS:
            raise ProtocolError(f"unknown handle op {op!r}")
        if op == "issue" and not isinstance(envelope.get("spec"), dict):
            raise ProtocolError("handle op 'issue' requires a 'spec' object")
        if op == "resolve" and not envelope.get("handle") and not envelope.get("kind"):
            raise ProtocolError("handle op 'resolve' requires 'handle' or 'kind'")
    elif message_type == "handle_ack":
        if envelope.get("ok", True):
            has_result = any(key in envelope for key in ("handle", "candidates"))
            if not has_result:
                raise ProtocolError("successful handle_ack requires 'handle' or 'candidates'")
    elif message_type == "draft_ack":
        if envelope.get("ok", True):
            verdict = envelope.get("verdict")
            if verdict not in GATE_VERDICTS:
                raise ProtocolError("draft_ack verdict must be a Gate Kernel class")
            missing = envelope.get("missing", [])
            if not isinstance(missing, list) or any(not isinstance(m, str) for m in missing):
                raise ProtocolError("draft_ack 'missing' must be a list of strings")
    elif message_type == "reconcile_ack":
        if envelope.get("ok", True) and envelope.get("state") not in RECONCILE_STATES:
            raise ProtocolError("successful reconcile_ack requires a known 'state'")


def _infer_revoke_op(envelope: dict[str, Any]) -> str:
    if envelope.get("lease_id"):
        return "lease"
    if envelope.get("owner_key_hash") and envelope.get("session_id"):
        return "session"
    return ""


def canonical_json(value: Any) -> str:
    """Deterministic JSON used as the MAC pre-image (sorted keys, no spaces)."""

    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def compute_mac(session_key: bytes, envelope: dict[str, Any]) -> str:
    """HMAC-SHA256 over the canonical JSON of the envelope without ``mac``."""

    payload = {key: value for key, value in envelope.items() if key != "mac"}
    digest = hmac.new(session_key, canonical_json(payload).encode("utf-8"), hashlib.sha256)
    return MAC_PREFIX + digest.hexdigest()


def verify_mac(session_key: bytes, envelope: dict[str, Any]) -> bool:
    """Constant-time check of the envelope ``mac`` field."""

    presented = envelope.get("mac")
    if not isinstance(presented, str) or not presented.startswith(MAC_PREFIX):
        return False
    expected = compute_mac(session_key, envelope)
    return hmac.compare_digest(presented, expected)


def _check_depth(value: Any, depth: int = 0) -> bool:
    if depth > MAX_JSON_DEPTH:
        return False
    if isinstance(value, dict):
        return all(_check_depth(item, depth + 1) for item in value.values())
    if isinstance(value, list):
        return all(_check_depth(item, depth + 1) for item in value)
    return True


def _validate_fields(
    envelope: dict[str, Any],
    specs: tuple[FieldSpec, ...],
    *,
    reject_unknown: bool,
) -> None:
    known = {spec.name for spec in specs}
    if reject_unknown:
        for key in envelope:
            if key not in known and key not in {"seq", "nonce", "mac"}:
                raise ProtocolError(f"unknown field {key!r}")
    for spec in specs:
        if spec.name not in envelope:
            if spec.optional:
                continue
            raise ProtocolError(f"missing field {spec.name!r}")
        value = envelope[spec.name]
        kind_ok = isinstance(value, spec.kinds)
        if kind_ok and isinstance(value, bool) and bool not in spec.kinds:
            kind_ok = False
        if not kind_ok:
            raise ProtocolError(f"field {spec.name!r} has wrong type")
        if isinstance(value, str) and len(value) > spec.max_len:
            raise ProtocolError(f"field {spec.name!r} exceeds length cap")
        if (
            isinstance(value, int)
            and not isinstance(value, bool)
            and not spec.lo <= value <= spec.hi
        ):
            raise ProtocolError(f"field {spec.name!r} out of range")


def parse_frame(data: bytes) -> dict[str, Any]:
    """Decode one frame payload with strict envelope + schema validation.

    ``data`` must be the JSON payload (after the 4-byte length prefix was
    consumed). Raises :class:`ProtocolError` on any violation.
    """

    if len(data) > MAX_FRAME_BYTES:
        raise ProtocolError("frame exceeds 64KiB")
    try:
        envelope = json.loads(data.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise ProtocolError("frame is not valid UTF-8 JSON") from exc
    if not isinstance(envelope, dict):
        raise ProtocolError("frame payload must be a JSON object")
    if not _check_depth(envelope):
        raise ProtocolError("frame JSON depth exceeds 16")

    _validate_fields(envelope, ENVELOPE_FIELDS, reject_unknown=False)
    message_type = envelope["type"]
    if message_type not in MESSAGE_TYPES:
        raise ProtocolError(f"unknown message type {message_type!r}")
    _validate_fields(envelope, _SCHEMA[message_type], reject_unknown=True)
    _validate_ack_semantics(envelope)
    _validate_revoke_semantics(envelope)
    _validate_stageb_semantics(envelope)
    if message_type == "consume":
        validate_consume_request(envelope)
    elif message_type == "issue":
        lease_params = envelope.get("lease")
        if not isinstance(lease_params, dict):
            raise ProtocolError("issue requires a 'lease' parameter object")
        context_fields = envelope.get("context")
        if context_fields is not None and not isinstance(context_fields, dict):
            raise ProtocolError("issue 'context' must be an object")
        validate_issue_request(lease_params, context_fields)

    nonce = envelope["nonce"]
    if not _NONCE_RE.fullmatch(nonce):
        raise ProtocolError("nonce must be 16-64 urlsafe characters")
    mac = envelope.get("mac")
    if message_type in UNAUTHENTICATED_TYPES:
        if mac is not None:
            raise ProtocolError("handshake messages must not carry a mac")
    elif mac is None:
        raise ProtocolError("message requires a mac")
    return envelope


def encode_frame(envelope: dict[str, Any]) -> bytes:
    """Serialize an envelope to a length-prefixed frame (ready to send)."""

    payload = json.dumps(envelope, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    if len(payload) > MAX_FRAME_BYTES:
        raise ProtocolError("frame exceeds 64KiB")
    return len(payload).to_bytes(4, "big") + payload


def make_envelope(
    message_type: str,
    *,
    seq: int,
    nonce: str,
    session_key: bytes | None,
    **fields: Any,
) -> dict[str, Any]:
    """Build a valid envelope, attaching the MAC when authenticated."""

    envelope: dict[str, Any] = {
        "v": PROTOCOL_VERSION,
        "type": message_type,
        "seq": seq,
        "nonce": nonce,
        **fields,
    }
    if session_key is not None:
        if message_type in UNAUTHENTICATED_TYPES:
            raise ProtocolError("handshake messages must not carry a mac")
        envelope["mac"] = compute_mac(session_key, envelope)
    parse_frame(canonical_json(envelope).encode("utf-8"))
    return envelope


def validate_lease_dict(lease: dict[str, Any]) -> None:
    """Strict shape check for serialized CapabilityLease payloads."""

    required_strings = (
        "lease_id",
        "owner_key_hash",
        "run_id",
        "tool_name",
        "args_schema",
        "resource_scope",
        "nonce",
    )
    for key in required_strings:
        value = lease.get(key)
        if not isinstance(value, str) or not value:
            raise ProtocolError(f"lease field {key!r} must be a non-empty string")
        if len(value) > 256:
            raise ProtocolError(f"lease field {key!r} exceeds length cap")
    mac = lease.get("mac")
    if not isinstance(mac, str) or not _LEASE_MAC_RE.fullmatch(mac):
        raise ProtocolError("lease mac must be 64 lowercase hex chars")
    for key in ("product_id", "session_id"):
        value = lease.get(key, "")
        if not isinstance(value, str) or len(value) > 256:
            raise ProtocolError(f"lease field {key!r} must be a bounded string")
    for key in ("fs_roots", "network_hosts"):
        value = lease.get(key, ())
        if not isinstance(value, (list, tuple)) or any(
            not isinstance(item, str) or len(item) > 4096 for item in value
        ):
            raise ProtocolError(f"lease field {key!r} must be a list of bounded strings")
    network_policy = lease.get("network_policy", "deny")
    if network_policy not in ("allow", "deny"):
        raise ProtocolError("lease network_policy must be allow|deny")
    for key in ("max_bytes", "max_duration_ms", "expires_at"):
        value = lease.get(key)
        if not isinstance(value, int) or isinstance(value, bool) or not 0 <= value <= MAX_SEQ:
            raise ProtocolError(f"lease field {key!r} must be a u64 integer")
    max_invocations = lease.get("max_invocations")
    if (
        not isinstance(max_invocations, int)
        or isinstance(max_invocations, bool)
        or not 1 <= max_invocations <= (1 << 32)
    ):
        raise ProtocolError("lease max_invocations must be a positive u32")
    parent = lease.get("parent_lease_id")
    if parent is not None and (not isinstance(parent, str) or len(parent) > 64):
        raise ProtocolError("lease parent_lease_id must be a bounded string")


def validate_issue_request(
    lease: dict[str, Any],
    context: dict[str, Any] | None,
) -> None:
    """Validate an issue request payload (params, not yet a lease)."""

    required_strings = (
        "owner_key_hash",
        "run_id",
        "tool_name",
        "args_schema",
        "resource_scope",
    )
    for key in required_strings:
        value = lease.get(key)
        if not isinstance(value, str) or not value:
            raise ProtocolError(f"issue field {key!r} must be a non-empty string")
    for key in ("fs_roots", "network_hosts"):
        value = lease.get(key)
        if value is None:
            continue
        if not isinstance(value, (list, tuple)) or any(not isinstance(item, str) for item in value):
            raise ProtocolError(f"issue field {key!r} must be a list of strings")
    network_policy = lease.get("network_policy", "deny")
    if network_policy not in ("allow", "deny"):
        raise ProtocolError("issue network_policy must be allow|deny")
    for key in ("max_bytes", "max_duration_ms", "ttl_ms"):
        value = lease.get(key)
        if not isinstance(value, int) or isinstance(value, bool) or not 0 <= value <= MAX_SEQ:
            raise ProtocolError(f"issue field {key!r} must be a u64 integer")
    max_invocations = lease.get("max_invocations", 1)
    if (
        not isinstance(max_invocations, int)
        or isinstance(max_invocations, bool)
        or max_invocations < 1
    ):
        raise ProtocolError("issue max_invocations must be >= 1")
    if context is not None:
        profile = context.get("profile", "")
        if not isinstance(profile, str) or len(profile) > 256:
            raise ProtocolError("issue context profile must be a bounded string")


def validate_consume_request(envelope: dict[str, Any]) -> None:
    """Mode-aware structural validation for a consume request.

    The daemon always uses its own clock; requests carry no time field by
    design (client time is untrusted).
    """

    mode = envelope.get("mode")
    if mode not in CONSUME_MODES:
        raise ProtocolError(f"unknown consume mode {mode!r}")
    if mode == "scan":
        scan_text = envelope.get("scan_text")
        session_id = envelope.get("session_id")
        if not isinstance(scan_text, str) or not scan_text:
            raise ProtocolError("consume mode 'scan' requires non-empty scan_text")
        if not isinstance(session_id, str) or not session_id:
            raise ProtocolError("consume mode 'scan' requires session_id")
        return
    if mode == "context":
        if "context" not in envelope:
            raise ProtocolError("consume mode 'context' requires 'context'")
        return
    if mode == "cell":
        payload = envelope.get("payload")
        if not isinstance(payload, dict):
            raise ProtocolError("consume mode 'cell' requires a 'payload' object")
        if set(payload) == {"draft_id"}:
            draft_id = payload.get("draft_id")
            if (
                not isinstance(draft_id, str)
                or not draft_id.startswith("draft:")
                or len(draft_id) > 256
            ):
                raise ProtocolError("draft consumption requires a bounded 'draft:' id")
            return
        if "draft_id" in payload:
            raise ProtocolError("draft consumption payload must contain only 'draft_id'")
        cell = payload.get("cell")
        if not isinstance(cell, str) or not cell.startswith("cell."):
            raise ProtocolError(
                "cell payload must name a 'cell.*' capability or contain only 'draft_id'"
            )
        return
    if "lease" not in envelope:
        raise ProtocolError(f"consume mode {mode!r} requires 'lease'")
    validate_lease_dict(envelope["lease"])
    expected = envelope.get("expected")
    if mode == "verify":
        if not isinstance(expected, dict):
            raise ProtocolError("consume mode 'verify' requires 'expected'")
        for key in ("owner", "tool", "scope"):
            if not isinstance(expected.get(key), str):
                raise ProtocolError(f"verify expected field {key!r} must be a string")
        return
    if mode == "preflight":
        if not isinstance(expected, dict):
            raise ProtocolError("consume mode 'preflight' requires 'expected'")
        _validate_bound_expected(expected)
        return
    # mode == "consume": expected present → bound consume, absent → plain consume
    if expected is not None:
        _validate_bound_expected(expected)


def _validate_bound_expected(expected: dict[str, Any]) -> None:
    string_keys = (
        "product_id",
        "owner_key_hash",
        "session_id",
        "run_id",
        "tool_name",
        "args_schema",
        "resource_scope",
        "network_policy",
    )
    for key in string_keys:
        if not isinstance(expected.get(key), str):
            raise ProtocolError(f"expected field {key!r} must be a string")
    for key in ("fs_roots", "network_hosts"):
        value = expected.get(key)
        if not isinstance(value, (list, tuple)) or any(not isinstance(item, str) for item in value):
            raise ProtocolError(f"expected field {key!r} must be a list of strings")
    for key in ("max_bytes", "max_duration_ms"):
        value = expected.get(key)
        if not isinstance(value, int) or isinstance(value, bool) or not 0 <= value <= MAX_SEQ:
            raise ProtocolError(f"expected field {key!r} must be a u64 integer")
    single = expected.get("require_single_use", True)
    if not isinstance(single, bool):
        raise ProtocolError("expected require_single_use must be a boolean")


__all__ = [
    "CELL_CONNECT_CAPS",
    "CLIENT_CAPS",
    "CONSUME_MODES",
    "EchoContextPayload",
    "ERROR_CODES",
    "GATE_VERDICTS",
    "HANDLE_OPS",
    "HEARTBEAT_INTERVAL_S",
    "REQUEST_TIMEOUT_S",
    "INTENT_OPS",
    "MAC_PREFIX",
    "MAX_FRAME_BYTES",
    "MAX_JSON_DEPTH",
    "MAX_SEQ",
    "MAX_STRING_LENGTH",
    "MESSAGE_TYPES",
    "NONCE_HEX_LENGTH",
    "PROTOCOL_VERSION",
    "ProtocolError",
    "RATE_LIMIT_BURST",
    "RATE_LIMIT_PER_SECOND",
    "RECONCILE_STATES",
    "REQUIRED_CAP",
    "REVOKE_OPS",
    "SERVER_CAPS",
    "SERVER_QUEUE_DEPTH",
    "SESSION_KEY_BYTES",
    "STAGE_B_CLIENT_CAPS",
    "STAGE_B_SERVER_CAPS",
    "VERDICTS",
    "canonical_json",
    "compute_mac",
    "encode_frame",
    "make_envelope",
    "parse_frame",
    "validate_consume_request",
    "validate_issue_request",
    "validate_lease_dict",
    "verify_mac",
]
